import React, { useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';

const root = document.getElementById('skillhub-cta-motion');

function SkillHubCta({ actionUrl, actionLabel }) {
    const sectionRef = useRef(null);
    const reducedMotion = useReducedMotion();
    const { scrollYProgress } = useScroll({ target: sectionRef, offset: ['start end', 'end start'] });
    const panelY = useTransform(scrollYProgress, [0, .5, 1], reducedMotion ? [0, 0, 0] : [34, 0, -22]);
    const accentY = useTransform(scrollYProgress, [0, 1], reducedMotion ? [0, 0] : [-18, 28]);

    return <section id="cara-kerja" ref={sectionRef} className="cta-motion-section">
        <style>{`
            .cta-motion-section{padding:clamp(5rem,8vw,8rem) clamp(1rem,3vw,4.5rem);background:#fff;color:#080808}.cta-motion-wrap{position:relative;max-width:1540px;margin:auto;border-top:1px solid #111;border-bottom:1px solid #111;padding:1px 0}.cta-motion-panel{position:relative;overflow:hidden;display:grid;grid-template-columns:minmax(0,1.55fr) minmax(360px,.45fr);gap:clamp(3rem,7vw,9rem);min-height:clamp(500px,58vw,660px);background:#f7f7f7;padding:clamp(2.5rem,7vw,7.5rem)}.cta-motion-panel::before{content:'';position:absolute;width:46rem;height:46rem;right:-17rem;bottom:-28rem;border:1px solid rgba(0,0,0,.17);border-radius:50%}.cta-motion-copy{position:relative;z-index:2}.cta-motion-kicker{margin:0;font-size:.72rem;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:#666}.cta-motion-title{max-width:950px;margin:1rem 0 0;font-size:clamp(3.2rem,6.8vw,7.7rem);line-height:.86;letter-spacing:-.1em;font-weight:700}.cta-motion-title span{color:#777}.cta-motion-description{max-width:560px;margin:2rem 0 0;font-size:1.05rem;line-height:1.65;color:#555}.cta-motion-button{display:inline-flex;align-items:center;gap:1.2rem;margin-top:2.5rem;padding:1.05rem 1.2rem 1.05rem 1.5rem;background:#080808;color:#fff;text-decoration:none;font-size:.85rem;font-weight:700;letter-spacing:.03em;transition:background .2s,transform .2s}.cta-motion-button:hover{background:#333;transform:translateY(-2px)}.cta-motion-button:active{transform:translateY(1px) scale(.98)}.cta-motion-button b{display:grid;place-items:center;width:2rem;height:2rem;background:#fff;color:#080808;font-size:1.2rem;font-weight:400}.cta-motion-aside{position:relative;z-index:2;align-self:end;border-left:1px solid #111;padding:0 0 0 clamp(1.5rem,3vw,3rem)}.cta-motion-aside p{margin:0}.cta-motion-index{font-size:.72rem;font-weight:700;letter-spacing:.13em;color:#777}.cta-motion-aside h3{margin:1rem 0 0;font-size:clamp(1.6rem,2.3vw,2.4rem);line-height:.95;letter-spacing:-.07em}.cta-motion-list{margin:2.4rem 0 0;padding:0;list-style:none;border-top:1px solid rgba(0,0,0,.2)}.cta-motion-list li{display:flex;justify-content:space-between;gap:1rem;padding:1rem 0;border-bottom:1px solid rgba(0,0,0,.2);font-size:.8rem;font-weight:700}.cta-motion-list li span:last-child{color:#777}.cta-motion-label{position:absolute;right:2rem;top:1.8rem;font-size:.68rem;font-weight:700;letter-spacing:.15em;color:#777;writing-mode:vertical-rl}@media(max-width:760px){.cta-motion-section{padding-inline:1rem}.cta-motion-panel{grid-template-columns:1fr;min-height:0;padding:2.5rem 1.5rem 3rem}.cta-motion-aside{margin-top:2rem;border-left:0;border-top:1px solid #111;padding:1.75rem 0 0}.cta-motion-label{display:none}.cta-motion-title{font-size:clamp(2.8rem,13vw,5rem)}}
        `}</style>
        <div className="cta-motion-wrap"><motion.div className="cta-motion-panel" style={{ y: panelY }} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .65, ease: [0.16, 1, .3, 1] }}><motion.span className="cta-motion-label" style={{ y: accentY }}>MULAI SEKARANG</motion.span><div className="cta-motion-copy"><p className="cta-motion-kicker">Jadikan keahlianmu terlihat</p><h2 className="cta-motion-title">Punya keahlian? <span>Jadikan peluang bersama SkillHub.</span></h2><p className="cta-motion-description">Tampilkan jasa yang kamu kuasai, temukan pemesan dari lingkungan sekolah, dan bangun portofolio dari pekerjaan nyata.</p><a className="cta-motion-button" href={actionUrl}>{actionLabel}<b aria-hidden="true">→</b></a></div><aside className="cta-motion-aside"><p className="cta-motion-index">01 — MULAI DARI SINI</p><h3>Kerja nyata.<br />Portofolio nyata.</h3><ul className="cta-motion-list"><li><span>Buat profil jasa</span><span>01</span></li><li><span>Terhubung dengan pemesan</span><span>02</span></li><li><span>Kembangkan kemampuan</span><span>03</span></li></ul></aside></motion.div></div>
    </section>;
}

if (root) createRoot(root).render(<SkillHubCta actionUrl={root.dataset.actionUrl} actionLabel={root.dataset.actionLabel} />);
