const fs = require('fs'); 
let content = fs.readFileSync('resources/views/admin/dashboard_new.blade.php', 'utf8'); 
content = content.replace(/body \{ font-family: .DM Sans., sans-serif; background: #f8f8f8; \}/, 'body { font-family: \" DM "Sans\, sans-serif; background: #FAFAFA; }'); 
content = content.replace(/:root \{[\s\S]*?--shadow-md: 0 4px 12px rgba\(0,0,0,0.08\);/, ':root {\n            /* Neutrals - 60% */\n            --bg: #FAFAFA;\n            --bg-card: #FFFFFF;\n            --border-strong: #000000;\n            --border-subtle: #E0E0E0;\n            --text: #111111;\n            --text-secondary: #555555;\n            --text-muted: #999999;\n\n            /* Primary - 30% */\n            --black: #000000;\n\n            /* Accent - 10% */\n            --accent: #E4002B;\n            --accent-hover: #C40025;\n            --success: #2C9F45;\n            --warning: #EDE734;\n\n            /* Spacing scale (4px base) */\n            --space-1: 4px;   --space-2: 8px;   --space-3: 12px;\n            --space-4: 16px;  --space-6: 24px;  --space-8: 32px;\n            --space-12: 48px; --space-16: 64px; --space-24: 96px;\n\n            /* Radius */\n            --radius-sm: 4px;\n            --radius-md: 8px;\n            --radius-lg: 16px;\n\n            /* Shadows - max 2 elevations */\n            --shadow-card: 0 1px 3px rgba(0,0,0,0.06);\n            --shadow-hover: 0 4px 12px rgba(0,0,0,0.08);'); 
content = content.replace(/\.stat-card \{ transition: transform 150ms ease-out, box-shadow 150ms ease-out; \}\s+\.stat-card:hover \{ transform: translateY\(-2px\); \}/, '.stat-card { transition: transform 150ms ease-out, box-shadow 150ms ease-out; }\n        .stat-card:hover { transform: translateY(-2px); box-shadow: var(--shadow-hover); }'); 
content = content.replace(/\.badge \{ font-size: 10px; letter-spacing: 0.05em; \}/, '.badge { font-size: 12px; font-weight: 500; letter-spacing: 0.08em; text-transform: uppercase; }'); 
content = content.replace(/\[x-cloak\] \{ display: none !important; \}/, '[x-cloak] { display: none !important; }\n        .skeleton-pulse {\n            animation: skeleton-pulse 1.5s ease-in-out infinite;\n            background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);\n            background-size: 200% 100%;\n            border-radius: var(--radius-md);\n        }\n        @keyframes skeleton-pulse {\n            0% { background-position: -200% 0; }\n            100% { background-position: 200% 0; }\n        }'); 
fs.writeFileSync('resources/views/admin/dashboard_new.blade.php', content); 
console.log('Done'); 
