param(
    [ValidateSet('local', 'public')]
    [string] $Mode = 'local'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $projectRoot '.env'
$configFile = Join-Path $projectRoot 'public\realtime-config.js'

if (-not (Test-Path -LiteralPath $envFile)) {
    Write-Error '.env was not found.'
    exit 1
}

$keyLine = Get-Content -LiteralPath $envFile | Where-Object { $_ -match '^REVERB_APP_KEY=' } | Select-Object -First 1
if (-not $keyLine) {
    Write-Error 'REVERB_APP_KEY is missing from .env.'
    exit 1
}

$reverbKey = ($keyLine -replace '^REVERB_APP_KEY=', '').Trim().Trim('"').Trim("'")
if ([string]::IsNullOrWhiteSpace($reverbKey)) {
    Write-Error 'REVERB_APP_KEY is empty.'
    exit 1
}

$reverbHost = '127.0.0.1'
$port = 8080
$scheme = 'http'

if ($Mode -eq 'public') {
    try {
        $tunnels = (Invoke-RestMethod -Uri 'http://127.0.0.1:4040/api/tunnels' -TimeoutSec 3).tunnels
        $reverbTunnel = $tunnels | Where-Object {
            $_.public_url -match '^https://' -and $_.config.addr -match '(^|:|/)(127\.0\.0\.1|localhost):8000$'
        } | Select-Object -First 1
    } catch {
        exit 1
    }

    if (-not $reverbTunnel) {
        exit 1
    }

    $publicUri = [Uri] $reverbTunnel.public_url
    $reverbHost = $publicUri.Host
    $port = 443
    $scheme = 'https'
}

$safeKey = $reverbKey.Replace("'", "\\'")
$safeHost = $reverbHost.Replace("'", "\\'")
$content = @"
// Generated by start-midtrans-setup.bat. Do not commit tunnel-specific values.
window.SkillHubRealtime = Object.assign(window.SkillHubRealtime || {}, { key: '$safeKey', host: '$safeHost', port: $port, scheme: '$scheme' });
"@

Set-Content -LiteralPath $configFile -Value $content -NoNewline -Encoding utf8
exit 0
